"""HTML report generator for EKS upgrade plans."""

from typing import Dict, Any
from datetime import datetime
from src.utils.logger import get_logger

logger = get_logger(__name__)


class HTMLReporter:
    """Generate HTML format upgrade reports."""

    def __init__(self):
        """Initialize HTML reporter."""
        pass

    def generate_report(
        self,
        cluster_info: Dict[str, Any],
        scan_results: Dict[str, Any],
        analysis_results: Dict[str, Any],
        upgrade_plan: Dict[str, Any],
        risk_assessment: Dict[str, Any],
        migration_plan: Dict[str, Any],
    ) -> str:
        """
        Generate comprehensive HTML upgrade report.

        Args:
            cluster_info: Cluster information
            scan_results: Scan results
            analysis_results: Analysis results
            upgrade_plan: Upgrade plan
            risk_assessment: Risk assessment
            migration_plan: Migration plan

        Returns:
            HTML formatted report
        """
        logger.info("Generating HTML report")

        cluster = cluster_info.get("cluster", {})
        cluster_name = cluster.get("name", "Unknown")
        current_version = cluster.get("version", "Unknown")
        target_version = (
            upgrade_plan.get("upgrade_path", [])[-1]
            if upgrade_plan.get("upgrade_path")
            else "Unknown"
        )
        risk_level = risk_assessment.get("overall_risk", "UNKNOWN")

        # Risk level color
        risk_colors = {
            "LOW": "#28a745",
            "MEDIUM": "#ffc107",
            "HIGH": "#fd7e14",
            "CRITICAL": "#dc3545",
        }
        risk_color = risk_colors.get(risk_level, "#6c757d")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EKS Upgrade Plan - {cluster_name}</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>EKS Upgrade Plan: {cluster_name}</h1>
            <div class="metadata">
                <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                <p><strong>Current Version:</strong> {current_version}</p>
                <p><strong>Target Version:</strong> {target_version}</p>
                <p><strong>Risk Level:</strong> <span class="risk-badge" style="background-color: {risk_color}">{risk_level}</span></p>
            </div>
        </header>

        <nav class="toc">
            <h2>Table of Contents</h2>
            <ul>
                <li><a href="#summary">Executive Summary</a></li>
                <li><a href="#current-state">Current State</a></li>
                <li><a href="#upgrade-path">Upgrade Path</a></li>
                <li><a href="#requirements">Pre-Upgrade Requirements</a></li>
                <li><a href="#deprecated">Deprecated APIs</a></li>
                <li><a href="#breaking">Breaking Changes</a></li>
                <li><a href="#migration">Migration Requirements</a></li>
                <li><a href="#steps">Upgrade Steps</a></li>
                <li><a href="#risk">Risk Assessment</a></li>
                <li><a href="#rollback">Rollback Plan</a></li>
                <li><a href="#timeline">Timeline</a></li>
            </ul>
        </nav>

        {self._generate_summary_section(cluster_info, upgrade_plan, risk_assessment)}
        {self._generate_current_state_section(cluster_info)}
        {self._generate_upgrade_path_section(upgrade_plan)}
        {self._generate_requirements_section(upgrade_plan, analysis_results)}
        {self._generate_deprecated_apis_section(analysis_results)}
        {self._generate_breaking_changes_section(analysis_results)}
        {self._generate_migration_section(migration_plan)}
        {self._generate_steps_section(upgrade_plan)}
        {self._generate_risk_section(risk_assessment)}
        {self._generate_rollback_section()}
        {self._generate_timeline_section(upgrade_plan)}

        <footer>
            <p>Generated by EKS Upgrade Planner v1.0.0</p>
        </footer>
    </div>
</body>
</html>"""

        logger.info("HTML report generated successfully")
        return html

    def _get_css(self) -> str:
        """Get CSS styling for HTML report."""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        
        header {
            border-bottom: 3px solid #007bff;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        
        h1 {
            color: #007bff;
            margin-bottom: 15px;
        }
        
        h2 {
            color: #495057;
            margin-top: 30px;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #dee2e6;
        }
        
        h3 {
            color: #6c757d;
            margin-top: 20px;
            margin-bottom: 10px;
        }
        
        .metadata {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
        }
        
        .metadata p {
            margin: 5px 0;
        }
        
        .risk-badge {
            display: inline-block;
            padding: 3px 10px;
            border-radius: 3px;
            color: white;
            font-weight: bold;
        }
        
        .toc {
            background-color: #e9ecef;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 30px;
        }
        
        .toc ul {
            list-style-position: inside;
            margin-left: 20px;
        }
        
        .toc a {
            color: #007bff;
            text-decoration: none;
        }
        
        .toc a:hover {
            text-decoration: underline;
        }
        
        section {
            margin-bottom: 40px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #dee2e6;
        }
        
        th {
            background-color: #007bff;
            color: white;
        }
        
        tr:hover {
            background-color: #f8f9fa;
        }
        
        ul, ol {
            margin-left: 30px;
            margin-bottom: 15px;
        }
        
        li {
            margin: 8px 0;
        }
        
        .warning {
            background-color: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin: 15px 0;
        }
        
        .danger {
            background-color: #f8d7da;
            border-left: 4px solid #dc3545;
            padding: 15px;
            margin: 15px 0;
        }
        
        .success {
            background-color: #d4edda;
            border-left: 4px solid #28a745;
            padding: 15px;
            margin: 15px 0;
        }
        
        .info {
            background-color: #d1ecf1;
            border-left: 4px solid #17a2b8;
            padding: 15px;
            margin: 15px 0;
        }
        
        footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            text-align: center;
            color: #6c757d;
        }
        
        code {
            background-color: #f8f9fa;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }
        """

    def _generate_summary_section(
        self,
        cluster_info: Dict[str, Any],
        upgrade_plan: Dict[str, Any],
        risk_assessment: Dict[str, Any],
    ) -> str:
        """Generate executive summary section."""
        cluster = cluster_info.get("cluster", {})
        upgrade_path = upgrade_plan.get("upgrade_path", [])
        time_est = upgrade_plan.get("time_estimation", {})

        return f"""
        <section id="summary">
            <h2>Executive Summary</h2>
            <ul>
                <li><strong>Current EKS Version:</strong> {cluster.get('version', 'Unknown')}</li>
                <li><strong>Target EKS Version:</strong> {upgrade_path[-1] if upgrade_path else 'Unknown'}</li>
                <li><strong>Risk Level:</strong> {risk_assessment.get('overall_risk', 'UNKNOWN')}</li>
                <li><strong>Estimated Effort:</strong> {time_est.get('total_hours', 'Unknown')} hours</li>
                <li><strong>Version Jumps Required:</strong> {len(upgrade_path) - 1 if upgrade_path else 0}</li>
            </ul>
        </section>
        """

    def _generate_current_state_section(self, cluster_info: Dict[str, Any]) -> str:
        """Generate current state section."""
        cluster = cluster_info.get("cluster", {})
        node_groups = cluster_info.get("node_groups", [])
        addons = cluster_info.get("addons", [])

        ng_table = self._generate_node_groups_table(node_groups)
        addon_table = self._generate_addons_table(addons)

        return f"""
        <section id="current-state">
            <h2>Current State</h2>
            <ul>
                <li><strong>Cluster Name:</strong> {cluster.get('name', 'Unknown')}</li>
                <li><strong>EKS Version:</strong> {cluster.get('version', 'Unknown')}</li>
                <li><strong>Status:</strong> {cluster.get('status', 'Unknown')}</li>
                <li><strong>Node Groups:</strong> {len(node_groups)}</li>
                <li><strong>Addons:</strong> {len(addons)}</li>
            </ul>
            
            <h3>Node Groups</h3>
            {ng_table}
            
            <h3>Installed Addons</h3>
            {addon_table}
        </section>
        """

    def _generate_node_groups_table(self, node_groups) -> str:
        """Generate node groups table."""
        if not node_groups:
            return "<p>No node groups found.</p>"

        rows = ""
        for ng in node_groups:
            name = ng.get("name", "N/A")
            version = ng.get("version", "N/A")
            ami_type = ng.get("ami_type", "N/A")
            desired = ng.get("scaling_config", {}).get("desiredSize", 0)
            instances = ", ".join(ng.get("instance_types", ["N/A"])[:2])

            rows += f"""
            <tr>
                <td>{name}</td>
                <td>{version}</td>
                <td>{ami_type}</td>
                <td>{desired}</td>
                <td>{instances}</td>
            </tr>
            """

        return f"""
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Version</th>
                    <th>AMI Type</th>
                    <th>Capacity</th>
                    <th>Instance Types</th>
                </tr>
            </thead>
            <tbody>
                {rows}
            </tbody>
        </table>
        """

    def _generate_addons_table(self, addons) -> str:
        """Generate addons table."""
        if not addons:
            return "<p>No addons installed.</p>"

        rows = ""
        for addon in addons:
            name = addon.get("name", "N/A")
            version = addon.get("version", "N/A")
            status = addon.get("status", "N/A")

            rows += f"""
            <tr>
                <td>{name}</td>
                <td>{version}</td>
                <td>{status}</td>
            </tr>
            """

        return f"""
        <table>
            <thead>
                <tr>
                    <th>Addon</th>
                    <th>Version</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {rows}
            </tbody>
        </table>
        """

    def _generate_upgrade_path_section(self, upgrade_plan: Dict[str, Any]) -> str:
        """Generate upgrade path section."""
        upgrade_path = upgrade_plan.get("upgrade_path", [])

        if not upgrade_path or len(upgrade_path) < 2:
            return '<section id="upgrade-path"><h2>Upgrade Path</h2><p>No upgrade needed.</p></section>'

        steps = ""
        for i, version in enumerate(upgrade_path, 1):
            if i == 1:
                steps += f"<li><strong>Current:</strong> EKS {version}</li>"
            else:
                steps += f"<li>✅ Upgrade to EKS {version}</li>"

        warning = ""
        if len(upgrade_path) > 2:
            warning = '<div class="warning">⚠️ <strong>Note:</strong> Cannot skip minor versions - sequential upgrades required</div>'

        return f"""
        <section id="upgrade-path">
            <h2>Upgrade Path</h2>
            <ol>
                {steps}
            </ol>
            {warning}
        </section>
        """

    def _generate_requirements_section(
        self, upgrade_plan: Dict[str, Any], analysis_results: Dict[str, Any]
    ) -> str:
        """Generate pre-upgrade requirements section."""
        addon_recs = analysis_results.get("addon_recommendations", [])

        items = ""
        for addon in addon_recs:
            if addon.get("action_required"):
                current = addon.get("current_version", "Unknown")
                recommended = addon.get("recommended_version", "Unknown")
                items += f"<li>Update {addon.get('addon_name')}: {current} → {recommended}</li>"

        items += """
        <li>Backup cluster configuration and data</li>
        <li>Test upgrade in staging environment</li>
        <li>Review breaking changes documentation</li>
        <li>Prepare rollback plan</li>
        """

        return f"""
        <section id="requirements">
            <h2>Pre-Upgrade Requirements</h2>
            <ul>
                {items}
            </ul>
        </section>
        """

    def _generate_deprecated_apis_section(
        self, analysis_results: Dict[str, Any]
    ) -> str:
        """Generate deprecated APIs section."""
        deprecated_apis = analysis_results.get("deprecated_apis", {})

        if not deprecated_apis:
            return '<section id="deprecated"><h2>Deprecated APIs</h2><div class="success">✅ No deprecated APIs found</div></section>'

        total_count = sum(len(resources) for resources in deprecated_apis.values())

        content = f'<div class="warning">⚠️ {total_count} resources using deprecated APIs</div>'

        for api_version, resources in list(deprecated_apis.items())[:5]:  # Limit to 5
            deprecation_info = (
                resources[0].get("deprecation_info", {}) if resources else {}
            )
            replacement = deprecation_info.get("replacement", "N/A")
            removed_in = deprecation_info.get("removed_in", "N/A")

            content += f"""
            <h3>{api_version} (removed in {removed_in})</h3>
            <p><strong>Replacement:</strong> {replacement}</p>
            <ul>
            """

            for resource in resources[:5]:  # Limit to 5 per API version
                name = resource.get("name", "Unknown")
                kind = resource.get("kind", "Unknown")
                ns = resource.get("namespace", "default")
                content += f"<li>{kind} <code>{name}</code> in namespace <code>{ns}</code></li>"

            content += "</ul>"

        return f"""
        <section id="deprecated">
            <h2>Deprecated APIs Found</h2>
            {content}
        </section>
        """

    def _generate_breaking_changes_section(
        self, analysis_results: Dict[str, Any]
    ) -> str:
        """Generate breaking changes section."""
        breaking_changes = analysis_results.get("breaking_changes", [])

        if not breaking_changes:
            return '<section id="breaking"><h2>Breaking Changes</h2><div class="success">✅ No breaking changes identified</div></section>'

        content = ""
        for change in breaking_changes[:10]:  # Limit to 10
            impact = change.get("impact", "UNKNOWN")
            title = change.get("title", "Unknown")
            description = change.get("description", "")
            action = change.get("action", "Review manually")

            css_class = "danger" if impact == "HIGH" else "warning"

            content += f"""
            <div class="{css_class}">
                <h3>[{impact}] {title}</h3>
                <p>{description}</p>
                <p><strong>Action Required:</strong> {action}</p>
            </div>
            """

        return f"""
        <section id="breaking">
            <h2>Breaking Changes</h2>
            {content}
        </section>
        """

    def _generate_migration_section(self, migration_plan: Dict[str, Any]) -> str:
        """Generate migration requirements section."""
        if not migration_plan.get("migration_required"):
            return '<section id="migration"><h2>Migration Requirements</h2><div class="success">✅ No migrations required</div></section>'

        critical = migration_plan.get("critical_migrations", 0)
        total = migration_plan.get("total_resources_affected", 0)

        return f"""
        <section id="migration">
            <h2>Migration Requirements</h2>
            <div class="info">
                <p><strong>Manifest Updates Required:</strong> {total} resources</p>
                <p><strong>Critical Migrations:</strong> {critical}</p>
            </div>
        </section>
        """

    def _generate_steps_section(self, upgrade_plan: Dict[str, Any]) -> str:
        """Generate detailed upgrade steps section."""
        runbook = upgrade_plan.get("runbook", {})
        phases = runbook.get("phases", [])

        content = ""
        for i, phase in enumerate(phases, 1):
            phase_name = phase.get("phase", f"Phase {i}")
            duration = phase.get("duration", "Unknown")
            steps = phase.get("steps", [])

            steps_html = "".join(f"<li>{step}</li>" for step in steps)

            content += f"""
            <h3>Phase {i}: {phase_name}</h3>
            <p><strong>Estimated Duration:</strong> {duration}</p>
            <ol>
                {steps_html}
            </ol>
            """

        return f"""
        <section id="steps">
            <h2>Detailed Upgrade Steps</h2>
            {content}
        </section>
        """

    def _generate_risk_section(self, risk_assessment: Dict[str, Any]) -> str:
        """Generate risk assessment section."""
        risk_level = risk_assessment.get("overall_risk", "UNKNOWN")
        risk_factors = risk_assessment.get("risk_factors", [])
        mitigations = risk_assessment.get("mitigation_strategies", [])

        risk_factors_html = "".join(f"<li>{factor}</li>" for factor in risk_factors)
        mitigations_html = "".join(
            f"<li>{mitigation}</li>" for mitigation in mitigations
        )

        return f"""
        <section id="risk">
            <h2>Risk Assessment</h2>
            <p><strong>Overall Risk Level:</strong> {risk_level}</p>
            
            <h3>Risk Factors</h3>
            <ul>
                {risk_factors_html if risk_factors_html else '<li>None identified</li>'}
            </ul>
            
            <h3>Mitigation Strategies</h3>
            <ol>
                {mitigations_html if mitigations_html else '<li>No specific mitigations required</li>'}
            </ol>
        </section>
        """

    def _generate_rollback_section(self) -> str:
        """Generate rollback plan section."""
        return """
        <section id="rollback">
            <h2>Rollback Plan</h2>
            <div class="warning">
                <h3>Important Notes</h3>
                <p>EKS control plane upgrades cannot be rolled back. Plan carefully and test thoroughly.</p>
            </div>
            
            <h3>Node Group Rollback</h3>
            <ol>
                <li>Create new node group with previous AMI version</li>
                <li>Drain pods from upgraded nodes</li>
                <li>Delete upgraded node group</li>
                <li>Verify all workloads are healthy</li>
            </ol>
            
            <h3>Application Rollback</h3>
            <ol>
                <li>Revert manifest changes using backups</li>
                <li>Re-deploy previous application versions</li>
                <li>Verify functionality</li>
            </ol>
        </section>
        """

    def _generate_timeline_section(self, upgrade_plan: Dict[str, Any]) -> str:
        """Generate estimated timeline section."""
        time_est = upgrade_plan.get("time_estimation", {})
        breakdown = time_est.get("breakdown", {})

        breakdown_html = ""
        for category, time in breakdown.items():
            formatted_category = category.replace("_", " ").title()
            breakdown_html += f"<li><strong>{formatted_category}:</strong> {time}</li>"

        return f"""
        <section id="timeline">
            <h2>Estimated Timeline</h2>
            <ul>
                {breakdown_html}
            </ul>
            <p><strong>Total Estimated Time:</strong> {time_est.get('total_hours', 'Unknown')} hours</p>
            <p><strong>Recommended Maintenance Window:</strong> {time_est.get('recommended_window', 'Unknown')}</p>
        </section>
        """
