# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['build_entry.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('data', 'data'),
        ('config', 'config'),
    ],
    hiddenimports=[
        'src',
        'src.cli',
        'src.utils',
        'src.utils.logger',
        'src.utils.aws_helper',
        'src.utils.k8s_helper',
        'src.utils.cache',
        'src.scanner',
        'src.scanner.eks_scanner',
        'src.scanner.k8s_scanner',
        'src.analyzer',
        'src.analyzer.compatibility',
        'src.analyzer.deprecation',
        'src.analyzer.release_notes',
        'src.planner',
        'src.planner.upgrade_path',
        'src.planner.risk_assessment',
        'src.planner.migration_plan',
        'src.reporter',
        'src.reporter.markdown',
        'src.reporter.json_export',
        'src.reporter.html',
        'boto3',
        'botocore',
        'kubernetes',
        'yaml',
        'click',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='eks-upgrade-planner',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
